# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='published_date',
        ),
    ]
