# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ManyToManyField(to='portfolio.ProjectImage'),
        ),
    ]
