# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_projectimage_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(default=datetime.datetime(2016, 2, 10, 15, 33, 39, 29392, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
            preserve_default=False,
        ),
    ]
