# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20160210_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
