# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20160210_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 2, 10, 15, 46, 33, 56237, tzinfo=utc), upload_to='media'),
            preserve_default=False,
        ),
    ]
